package com.zenx.zen.hub;

public interface Tags {

    String MAIN_VIEW = "MAIN_VIEW";
    String STATUSBAR_FRAGMENT = "STATUSBAR_FRAGMENT";
    String QUICKSETTINGS_FRAGMENT = "QUICKSETTINGS_FRAGMENT";
    String STATUSBAR_QUICKSETTINGS_FRAGMENT = "STATUSBAR_QUICKSETTINGS_FRAGMENT";
    String NOTIFICATION_FRAGMENT = "NOTIFICATION_FRAGMENT";
    String HEADSUP_FRAGMENT = "HEADSUP_FRAGMENT";
    String NOTIFICATION_HEADSUP_FRAGMENT = "NOTIFICATION_HEADSUP_FRAGMENT";
    String LOCKSCREEN_FRAGMENT = "LOCKSCREEN_FRAGMENT";
    String AMBIENT_FRAGMENT = "AMBIENT_FRAGMENT";
    String LOCKSCREEN_AMBIENT_FRAGMENT = "LOCKSCREEN_AMBIENT_FRAGMENT";
    String BUTTON_FRAGMENT = "BUTTON_FRAGMENT";
    String POWERBUTTON_FRAGMENT = "POWERBUTTON_FRAGMENT";
    String VOLUMEBUTTON_FRAGMENT = "VOLUMEBUTTON_FRAGMENT";
    String BUTTON_POWER_VOLUME_FRAGMENT = "BUTTON_POWER_VOLUME_FRAGMENT";
    String STYLE_FRAGMENT = "STYLE_FRAGMENT";
    String SCREEN_FRAGMENT = "SCREEN_FRAGMENT";
    String ANIMATION_FRAGMENT = "ANIMATION_FRAGMENT";
    String STYLE_SCREEN_ANIMATION_FRAGMENT = "STYLE_SCREEN_ANIMATION_FRAGMENT";
    String MISC_FRAGMENT = "MISC_FRAGMENT";
    String BATTERY_FRAGMENT = "BATTERY_FRAGMENT";
    String MISC_BATTERY_FRAGMENT = "MISC_BATTERY_FRAGMENT";
    String LINKS_FRAGMENT = "MISC_FRAGMENT";
    String DEVS_FRAGMENT = "DEVS_FRAGMENT";
    String LINKS_DEVS_FRAGMENT = "LINKS_DEVS_FRAGMENT";

}
